# -*- coding: utf-8 -*-
"""
Created on Sat Sep 30 08:06:13 2017

@author: Joanne
"""
#import openpyxl
#from openpyxl import load_workbook
import pandas as pd
import os
import xlsxwriter 
import csv
import shutil

#directoryPath=(__file__)
directoryPath=os.path.dirname(os.path.realpath(__file__))
mainPath=os.path.dirname(directoryPath)

print(directoryPath)
print(mainPath) 

# First read master start file contining correct year to create new folder and files as well as a current account list.
STARTFILE = pd.ExcelFile(directoryPath + '/MasterStartFile.xlsx')
#STARTFILE = pd.ExcelFile('C:/Users/Joanne/Desktop/George/festival/MasterStartFile.xlsx')
A = STARTFILE.sheet_names
DF1 = STARTFILE.parse(A[0])

#YEAR=int(DF1['Year'][0]);           # Use this option to enter in manually in Excel sheet 'MasterStartFile.xlsx'
YEAR = input("Enter the festival year: ")   # User input when program is run.
print(YEAR)

ACCOUNTS=DF1['Accounts'];

# Create a new directory. Check to make sure it doesn't already exist.

newpath = mainPath+'/'+str(YEAR) 
if not os.path.exists(newpath):
    os.makedirs(newpath)

os.chdir(mainPath+'/'+str(YEAR))

# Copy main exetutable file to new directory and rename file
shutil.copy(directoryPath + '/MasterStartFile.xlsx',mainPath + '/' +str(YEAR) + '/MasterStartFile.xlsx')
os.rename(mainPath + '/' +str(YEAR) + '/MasterStartFile.xlsx',mainPath + '/' +str(YEAR) + '/MasterStartFile.xlsx')

# Copy main exetutable file to new directory and rename file
shutil.copy(directoryPath + '/MAIN.py',mainPath + '/' +str(YEAR) + '/MAIN.py')
os.rename(mainPath + '/' +str(YEAR) + '/MAIN.py',mainPath + '/' +str(YEAR) + '/MAIN' + str(YEAR) + '.py')

# Copy main exetutable file to new directory and rename file
shutil.copy(directoryPath + '/Final_report_supporting_data.xlsx',mainPath + '/' +str(YEAR) + '/Final_report_supporting_data.xlsx')
os.rename(mainPath + '/' +str(YEAR) + '/Final_report_supporting_data.xlsx',mainPath + '/' +str(YEAR) +'/Final_' +str(YEAR) + '_report_supporting_data.xlsx')


#import os
#import shutil
#def copy_rename(old_file_name, new_file_name):
#        src_dir= os.curdir
 #       dst_dir= os.path.join(os.curdir , "subfolder")
 #       src_file = os.path.join(src_dir, old_file_name)
  #      shutil.copy(src_file,dst_dir)
        
    #    dst_file = os.path.join(dst_dir, old_file_name)
     #   new_dst_file_name = os.path.join(dst_dir, new_file_name)
      #  os.rename(dst_file, new_dst_file_name)


# xlsx writer is a file creator function, NOT a function to modify existing files.
# Important to note! xlsxwriter WILL overwrite files.

# Create the main festival ledger file (Excel).
#workbook = xlsxwriter.Workbook('festival'+str(YEAR)+'.xlsx','a+')
workbook = xlsxwriter.Workbook('ledger_'+str(YEAR)+'.xlsx')
worksheet = workbook.add_worksheet()

#Note that the write function is 0,0 indexed (row,column).

# Create the top column headers in the file
accountList=['Transaction ID','Date','Type','Account','Amount','FestivalDays','Payment','RecvdFrom','CheckNumber','Payee','Description','DepositDate','Reconciled']

for i in range(0,len(accountList)):
    worksheet.write(0,i,accountList[i])
    
for i in range(1,(2*len(ACCOUNTS))+1):
    worksheet.write(i,1,'DO NOT INPUT TRANSACTIONS ON THIS LINE - RESERVED FOR AUTO FILL FROM FESTIVAL DAY TRANSACTIONS GENERATED BY PYTHON CODE')
    
# Create starting point for recording transactions in file. Initial rows are reserved for writing festival day summary.
#worksheet.write(2+(2*len(ACCOUNTS)),0,'INPUT TRANSACTIONS BELOW THIS LINE...INPUT TRANSACTIONS BELOW THIS LINE...INPUT TRANSACTIONS BELOW THIS LINE...')
workbook.close()

workbook2 = xlsxwriter.Workbook('accounts_'+str(YEAR)+'.xlsx')
worksheet2 = workbook2.add_worksheet()

#Note that the write function is 0,0 indexed (row,column).
worksheet2.write(0,0,'Account')
for i in range(0,len(ACCOUNTS)):
    worksheet2.write(i+1,0,ACCOUNTS[i])
    
workbook2.close()

# Create the starting csv file for recording all festival transactions.

with open('ledgerFestival_'+str(YEAR)+'.csv', 'w') as csvfile:
    fieldnames = ['amount', 'type','subType','account','subaccount','time','date','initials','comments']
    writer = csv.writer(csvfile)
    writer.writerow(fieldnames)
    
    
    
f= open("HelpFile.txt","w+")
f.write("-------------------------------------------------------------------------------------------\n")
f.write("This is a Help File for festival finance accounting\n")
f.write("-------------------------------------------------------------------------------------------\n\n")
f.write("*** XXXX refers to the festival year which is input in the masterStartFile.xlsx\n\n")
f.write("1. The main ledger file (ledger_XXXX.xlsx) is for capturing ALL transactions\nOUTSIDE of the festival ledger.\n")
f.write("Anything that is captured in the festival ledger during festival days should be kept separate to this ledger \notherwise")
f.write("any duplicate transactions will be double counted.\n\n")
f.write("2. The festival ledger file (ledgerFestival_XXXX.csv) is to be filled in AFTER the festival is over. This .csv file is filled in manually after the \nphysical ledger has")
f.write(" has been checked and signed off by all festival finance committee members who were present at the festival.\n\n")
f.write("3. A major file not included in the self generated file structure is the checking account transaction summary.\n")
f.write("Currently, the checking account we use is CapCom. If another checking account transaction summary file is used or\n if")
f.write("something in the CapCom summary has changed, the MAINXXXX.py code should be modified.")
f.close()

